#!/bin/sh

printf "use nix" > .envrc
printf "{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
	buildInputs = with pkgs; [
		# nodejs_24
		# nodejs_22

		# python314
		# python2

		# go
		# air
	];
}
" > shell.nix

direnv allow		
