#!/bin/sh

# Setting up the user's D-Bus Daemon
if test -z "$DBUS_SESSION_BUS_ADDRES"; then
	eval $(dbus-launch --exit-with-session --sh --syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

xrandr --output eDP-1 --off --output VGA-1 --primary --mode 1440x900 --rate 75 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off
bspc query -M --names | grep -F -v VGA-1 | xargs -r -n1 -I{} bspc monitor {} -r

for ps in sxhkd tint2; do
	pkill $ps > /dev/null; $ps &
done

feh --no-fehbg --bg-scale ~/Downloads/wallhaven-z8vmro.png &
numlockx on &

bspc monitor VGA-1 -d I II III IV V
bspc desktop ^3 --focus

# Monitor And Desktop Settings
bspc config top_padding		0
bspc config border_width	2
bspc config window_gap		10
bspc config focused_border_color '#ebdbb2'

# Global Settings
bspc config single_monocle true
bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config borderless_monocle true
bspc config focus_follows_pointer true

bspc config remove_disable_monitors true
bspc config remove_unplugged monitors true
bspc config merge_overlapping_monitors true
