#!/bin/sh

xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off
xrandr --output VGA-1 --primary --mode 1440x900 --rate 75 --pos 0x0 --rotate normal

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)

# Only have workspaces for primary monitor
bspc monitor $MONITOR -d I II III IV V
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Monitor And Desktop Settings
bspc config top_padding 0
bspc config border_width 2
bspc config window_gap 10
bspc config focused_border_color '#ebdbb2'

# Global Settings
bspc config single_monocle true
bspc config borderless_monocle true
bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true
bspc config pointer_follow_focus true

for ps in sxhkd tint2; do
	pkill $ps > /dev/null; $ps &
done

feh --no-fehbg --bg-fill ~/Downloads/wallhaven-w8rozq.jpg &
firefox &

# Rules
bspc rule -a Firefox -o desktop=III
